networks:
  app-tier:
    driver: bridge
services:
  coordinadoreventosapi:
    image: fing.idatos.coordinadoreventos.api
    ports:
      - "8080:8080"
    networks:
      - app-tier
    build:
      context: ./Backend/aspnet-core
      dockerfile: Dockerfile-Api
    depends_on:
      - db
    restart: on-failure
  coordinadoreventosmotor:
    image: fing.idatos.coordinadoreventos.motor
    ports:
      - "8088:8080"
    networks:
      - app-tier
    build:
      context: ./Backend/aspnet-core
      dockerfile: Dockerfile-Motor
    depends_on:
      - db
      - coordinadoreventosapi
    restart: on-failure
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "grdedb"
    networks:
      - app-tier
  logging:
    image: datalust/seq
    ports:
      - "8787:80"
    restart: always
    environment:
      ACCEPT_EULA: "Y"
    networks:
      - app-tier
    depends_on:
      - db
      - coordinadoreventosapi
      - coordinadoreventosmotor