networks:
  app-tier:
    driver: bridge
services:
  coordinadoreventosapi:
    image: fing.idatos.coordinadoreventos.api
    ports:
      - "8080:8080"
    networks:
      - app-tier
    build:
      context: ./Backend/aspnet-core
      dockerfile: Dockerfile-Api
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "grdedb"
    networks:
      - app-tier
    # volumes: 
    #   - db_volume:/var/lib/postgresql/data