networks:
  app-tier:
    driver: bridge
services:
  eventosapi:
    image: eventos-api
    ports:
      - "3000:3000"
    networks:
      - app-tier
    build:
      context: ./Backend/API
      dockerfile: Dockerfile
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0-debian
    expose:
      - "3312"
    ports:
      - "3312:3312"
    networks:
      - app-tier
    volumes:
        - ./Backend/SQL/schema.sql:/docker-entrypoint-initdb.d/init-script.sql
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_DATABASE: coordinador_eventos
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser